apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-secrets
    namespace: authentik
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:CEmcREEDi60PmNMzHg9rA2WBwjTPNf7T3fahHmTC7Jq2OHteUeqAc+De/eJuOHd+TCzgiNU=,iv:2U0DoxaSyUZvrNjLBbs363v+KSt1OtE7JknAWqa5LiA=,tag:gYau1yYzJ9if54MmNUgmBw==,type:str]
sops:
    age:
        - recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeGFHY2V1Yi9kbUR6UUpH
            OWVjVWcyRG0xYlNTVTdJNVc5V05UQlBCOG5nCnpucUdCMThlUW5wc1l1WGp6NE5R
            WFJadnduYkNuYjR1VFAyV2VCeEh0dUkKLS0tIFk4MmhjK1FYeDcyRWoza1RPS3I1
            YzlFWkYxODFKVWF5Q0NpeUZRTm1EN0UKC8xlJJGklPHHDe82TPaB02nx0VDQXkxG
            UInHO/tdUXMaywyyl5+U3mfksQVZ9FgO/1r383ZHiAsc/VkQ7+99Xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd3Y3SVdEcDhqQ001UzNh
            SWkwNVYyUlc3bXhjVGNDNmFwL0FySy8zbERRCm50VEUrQURTMTEyR04xbittL3RE
            d1NMVkNxU2NZVUN5amI4QyszdVYwQ00KLS0tIHB3dHY4VVF6NFkycjk2RmRFMUdp
            UXRST3phMEI5WlZNc3JMNVpYZHNRd2sKYCUx7k3nf4qxbUwK2CRdwn6qjTcgQyIF
            a+7vPkIZkCU0QG85ZD08pOKYoJaKWV6C5jlhWPmGHdLhHzyUbI/tTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-27T22:11:48Z"
    mac: ENC[AES256_GCM,data:aeIhJTkLouK/j47NEvUFJNgraBFg68FNw9PsgddjeaLrRC0sEmz596Rn1lInPoZG1iK1HRnGWDLJRENrI8D3uytRfXqf3TR/h9c6J0sitLbEyyTW3/1Zg9lYxJpw1LFuufMggk4eEyk5SNVuJkS2A1gMtyEpkucvIT4V+tTMSuY=,iv:YFyn/Zeyh2hKc9xkuoRnsMmcsLBtNIcqYCnkz/DUnS4=,tag:gKuiPwDSezexTGaYaS+oxA==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
