apiVersion: v1
kind: Secret
metadata:
    name: authentik-google-oauth
    namespace: authentik
type: Opaque
stringData:
    google-oauth-client-id: ENC[AES256_GCM,data:yMYcn/NGZ/8CKtapMYsJV26yN/NhruLB4QHnbR1RPOd8oHAAXngM,iv:vmvASTNE/8NJGFKBxKsdAyi90ugMSr+qsqHjpm6YOvQ=,tag:48NJE4hDl9Utw+RI0CgM7w==,type:str]
    google-oauth-client-secret: ENC[AES256_GCM,data:yOZcsKdQiyB/z5p7a/ohiBGZemfIDniFNOqwUiRX3mVEOjmE2BxFgjpksQ==,iv:OJEttAldLZPMLWETt5+psHsxJxlO/YNJ0Gf6M3V157M=,tag:DpiUZLfu3Mz0L6/Fvl717Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNklPNG9yZjF6eUtrdTNQ
            b2NTenlaRC9VV1NKOGh5TlpIUmMzRGswbnlFCmRJR3pSYkVIMmZLU3gxbjNRR2Z4
            RE5BZ08yaUt6ZVdlNnFhekFaL2RpZWMKLS0tIFJaVGswK2pmdFM3eUxMN0xYbExS
            YVZMUVh1NVV6NFFUenFuQXpNNFpnN3MKXuGNvM+wLu1tKWbhK2fxJuwaOXyx6See
            87gmF8QFKJnnfuDAW2WP+SAHi4dthB99Tg1sukkLjBRn2vcZ+gejEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcDVxSmU2ODhKY3Y2K0dj
            NTdHMnJLbjUwR0R5WXpvVVpraWNiTGRtWm1JCmtmUnRrd0UwVTBRVjVycC9ORjFM
            c2M1bFFzV3A1endLeHYrb1I3a3Y3aTgKLS0tIDVsVDZCSE5udTZVR3NmSlBqLytX
            ZnFTanVLS1doQ1VTYWk1M1dvaXZKbTAKuzVCBrO5z0FkvZUb5IsDNvggCuyWKn4j
            tbO3rAwGvqnzog5qcDbEpgqV4eTtlsuNf+qvSbqC5zDZI0vvzNaUqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-06-06T16:22:47Z"
    mac: ENC[AES256_GCM,data:erepWAn93VHn5OmF0y4/fo3O/3a2ESDDWsNAMNy0AUGEnmVpJKyzLLQ74Fki8cYSZHE0uRBINPSqEIBfkvngQUwYIzKfc7N+KsWFgmMSlGPgc+uKU6yCgOGCOmxM+saNHRWQHlDVu871leZpldHZSuMGYddLHkhaDEvSZ2qsu8U=,iv:0rHOBdbW6IFKlw56o9WOGCmy9Q8mhBdMtS7hh0uFnRs=,tag:9W5Ec4+xTA2HAm+iXrUIRg==,type:str]
    version: 3.13.1
