apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config/namespace.yaml
  - config/database-credentials.sops.yaml
  - config/authentik-env.sops.yaml
  - deployment/database.yaml
  - deployment/release.yaml
  - publication/ingress.yaml
  - publication/tunnel.yaml
  - publication/publication.yaml
