apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-app
    namespace: authentik
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:sYNQh3fYdF7i,iv:6rKMCD/CGJzYcOKlSbNwyNktVpSu1k38p2jvGRlavkw=,tag:8W0rLjZVL+W/DMRL9HiB0g==,type:str]
    password: ENC[AES256_GCM,data:3TaSc7id0Y9R,iv:O9+OEyw0S87I+dNXMLqM5Nn8be7Gnv+ERqSTFdK6Pso=,tag:R/76Rqql04vSr+SrvrUZ/w==,type:str]
    dbname: ENC[AES256_GCM,data:51lwgA33m4ug,iv:HV8LsdjW5WSs051E4zClF6Hb1gCys14ofpF5fSC7YHA=,tag:iorqgJL9b/NZxWy+kuMEcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVmI3UDZrUDN6cE8ybW8v
            OWFsNGpnOWxmQVhNYk8vUUoyRXE1TE5Vc0g4CkVmaHo4MTdvT0lqZ0Z4Nk9sNktU
            RFAxMjV4R2x6cTc3Zk5raW13SWNCTmcKLS0tIFRDdEJGNHk4UmVVeXJ3NGE3ODA4
            T3hUckxqYzFuRmwwRngzRFdpWEc5WnMKXHu/mgHc4aL/l36tUY9L0SqRMjUyYgLJ
            5pJSzmKloMTdjtoixmR5XUsOKUJASgTAwLazxJqrr66Nud+PFq6vjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWDFSSGdEMTcxQnROR2Js
            bVkvWXduZHkzT3lhSWFldUFNSEV0ZkZLalR3CkF4N1QrdlVpZUV3ZDB4SE1zU0FG
            K1ZxNHNvQjhZVHFHK2pKenBySDI0aGcKLS0tIFZBQjh1ckM4NGZVQ3hIYkxjQ3JX
            NHp5NkxsOE4xRkx6eXJydnZFSzNSZ00KQSgI+DFYQeRvGqp+NRnCcMjoPbL0m2y+
            4zyiNaZmoFXzu6O7dnpCMBRsSkvGPLiOxxXW8Yp1jYO5XMX29bKBFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-05-27T15:56:33Z"
    mac: ENC[AES256_GCM,data:UKxDShknp4J0OryCtdCahvFmelLKB+PuWOluVse5Bbi4c7oB+qjF1Y+GDDF6wSaIeuXh7GFsEXrwqTvttNJNWgRhH/m9hiTTqyfyH9QBHBOEv7724elOj9nxJDFw8Tpz6wp58aFTVd91PVDm+3SBupG6zMEX/go2Td6O4yewPRI=,iv:TFFRSrr/KlSj3/Bqg0QiUV0qMiN3OA8W2M2uSFMkeG8=,tag:uKGg8dDuDGIe/tdNz2YmuQ==,type:str]
    version: 3.13.0
