apiVersion: ENC[AES256_GCM,data:Aus=,iv:dLETlZo93ITVdrRMFC2L4BXg3N7IkQvQPI59UyiCKfs=,tag:fZKWkwiyIzJl1cT50ozlMw==,type:str]
kind: ENC[AES256_GCM,data:a7AoY56L,iv:ZcreonynmUOb4do27OVPXgWNt3kNq9l/1ChhKHKVHJc=,tag:pxJLCpLfHE9h9eByM0ucjg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:ODYWpXGrqEcsbgFe4iVu,iv:t8dK9MFgU7HCXYXwvVkmfDuq8pl3GYY3UBFPjp0eVAE=,tag:jh1KJ3GNpOcbQXPzJbzAhg==,type:str]
  namespace: ENC[AES256_GCM,data:FrSJuVmH1Jmyc34=,iv:rJhG8aB6BkSfKoqZPjCZYRUEt3/z9GjQC1+0tT+hcr8=,tag:vXGMlfHIt0IQzOqE1GDH2w==,type:str]
type: ENC[AES256_GCM,data:IeB2W2k8,iv:q2s1Ip3Dncye/srZ5zzbnznMKt4cOGVxxH/nkwi/5xg=,tag:W0rz7Yg4nIJX9JALLeL0tg==,type:str]
stringData:
  clientId: ENC[AES256_GCM,data:nQTZCopXZ+1CL7h1+fP2eCY=,iv:6dKhhPjVIvp9mnFPkXse0RFVoj5T+Qu4pm4vHaqCRHo=,tag:xHq9SfVjqSku/ezdDFUVPw==,type:str]
  clientSecret: ENC[AES256_GCM,data:n1QaasK1LpUmFHr3ugosPC91qr9L4HTK4r3/TP0cnsMYNB7GkeYT8InWRLkqY7ACDT71/1EA9zZJYlYva+cG,iv:omY2M7j/shwUSgoNegXXAxJ5thXKUI1poHmdwQUmiKU=,tag:S2k6VBk7Q7oGQCMfP0KiVw==,type:str]
sops:
  age:
    - recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPVjA4MU1lWFYzUVRSSy82
        RVJBV0tBbWN4MnAyYW90aHp5aVBpUUd0VlFBCnhLaDU1TTJ1c2lIdkdsaGQwRHRB
        UUNhZ1VoaTFNZ01UYjhlemJVc21CeVkKLS0tIFJrYzZ5NWpBZ1ppM0VoQTBPaGln
        ZUpXYWN0NytsYWRvY3N6T203d2VscUkKDoF3TseZtrZPppk2L8DcA2fjJXZRh6nF
        myj1gmCKdtcXYtaP1zFCEeScZv58+3Gu1Dpa2HwslmXYIp91y4vdog==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-03T06:15:18Z"
  mac: ENC[AES256_GCM,data:1qut7Q4NrzyEcuDKJXz3XyWT9N2ZXSjqUoyrX8OMLLbSKklVI7px+lfzREDUEeFJmU7Sc7vo32ZOYDFUiKMlyr/EkmRZIHfO01Na3v1Oza5Z+xDg/We2XWwO37i5w5dejsFtMoRDcadmUxCDoYXZQA1UsbGxDZM8ogjD3582VXs=,iv:4M5neQ+l4KWXIgLRLlyiCDRLM9y5hyZpHAQcVdDdED4=,tag:Re3UmDYlHx8Ix/X2C55ykw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.12.2
