services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_root_password
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - postgres
    secrets:
      - postgres_root_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3

  adminer:
    image: adminer:latest
    networks:
      - postgres
      - reverse-proxy_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.adminer.rule=Host(`db.admin.${DOMAIN_NAME}`)"
        - "traefik.http.routers.adminer.tls.certresolver=dnsresolver"
        - "traefik.http.routers.adminer.tls.certresolver=dnschallenge"
        - "traefik.http.services.adminer.loadbalancer.server.port=8080"

volumes:
  postgres_data:

secrets:
  postgres_root_password:
    file: ./secrets/postgres_root_password

networks:
  postgres:
    driver: overlay
    attachable: true
  reverse-proxy_public:
    external: true
