apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-app
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:5PYEyNxJi8+K,iv:sYMe34doUk1BRccbx1XF9QEjG3wful0xFT5JUCBmMZA=,tag:Jjf6A7ynNOjrB8AD06eedQ==,type:str]
    password: ENC[AES256_GCM,data:JiR+Qu9c+wOIhuuoUcXKLfc+dAsiuUP6HbxWNMydyBXRAVW4kLtYLx7e40w39czzBYOgB3CvKhGGvzsZDCh52g==,iv:0o5VaCsCp8VHQ+01aX7FEAlWiL5/PLmJFYt/Syo1zvI=,tag:eHRGDjnn4SOdGj0a9/Q1PA==,type:str]
sops:
    age:
        - recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMEx1QnQ3MkdZcEQvWUF3
            eUhHWEZWRWZIZ1lqTEoyKzU1UGQ5S0JUd0J3Cnl3cnphQ3Nubm9aL05wQk9EV0xk
            cmNmSHpER0s0MXljMU5JQnFtRS9RMEEKLS0tIFhWV0laNDNWSjIzeVpKTWszY0dO
            TWRjZWJkUDZndGMrclYvSlVsNGhMZmcKEYkNa3n103I2K1CeLOCCfHs2KyLbY2zB
            sjF4zwJXaTgebNiNI/uSay7GlC0IzdLWtd0tnXdo9hiKW6OLz2E5Hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ZFoyaHc0cG1qdEt5Vlow
            SDljcFA5dHlJWnhVOVQyT2MwRFNSaU9uZmdNClI2eUc1cFR6VjFwN1d2RjBrQkFG
            RTIvNUNwQVVZNkcvb0ZHQkcrM2Ztb3MKLS0tIFdMb0E2TCt6aFphcm56Nit6cEdR
            SHZBZjlZekFHV3dVNWZnMFdlSzRTTG8K/zT3SJVILbCDpj0ul5PAoIxfcTYuD7kx
            UiRXxkv4SlsbzuvxGjbBUVmVyAtI+uG5uQlu9tSLWCYdPqPLpgH3+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T18:12:13Z"
    mac: ENC[AES256_GCM,data:FzwijjagqNIPA41llnRab4SVirgtU5emcQvc48Ned8EPBGEHjd14XqDBGr8dK4+ATtneRlFXDCaFix+BuOgv58TyW/CElCIZkjosu9hwhjCjrfuhOiaMTY/WN0lEUZtyGkZktdVkhzGPs5pfrTCqr4jZSBB59jptmJIfPATwgqU=,iv:VAuaT4JgzIyh/sxm1DfhNXNaQ+upYhKVHSYOe/qZJ5M=,tag:NrSO1WXERus0Fztkjla1Wg==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
