apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-app
    namespace: authentik
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:CHFFlIIbSJ0D,iv:jmL+swmt+/WO9Dy+vxPQ3R9BsnyEXwl780dhH+r5SQ4=,tag:g0eJXZ2D85pvA9SghtqUPQ==,type:str]
    password: ENC[AES256_GCM,data:02WQajANdugOgXEuGQB3yp0KxNgZ7us5jy1L6cSkxXuXPbfZOvLvzImwdGYogAudVHzqZ3/CrvU5P4mh90C51w==,iv:U0ho+YXPVksqgAQzn/YGSUNUUDani7VTyNk2sevwoOI=,tag:qsr2ovtYjNbRnSsKFqaPQw==,type:str]
sops:
    age:
        - recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbnJTUXN6cXloSEZhZ1M4
            UGNWWDdva3dyZkZOT1RCR3oydE5CTGpDaWtJClNtM3lxVldwM290RzZNdTFjcjBa
            UXFTYm1yL3E2K0FiL0xRTWJDNDJTRVEKLS0tIHIwMzRabm40bkt5emwvTThVZ2Rs
            RUlDWXprbW54ZjUvenZpR1RPT1puVUEKQeyOZYktC6ywfBZTlK9tmnLtzdEiEU90
            IVJ2I7CbW6cm5aKAa933SvYySbL0cmYeCuOb1LAXcnL1tflV4ZPJWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvT004Vm5KTlNPMXZFT2ZD
            UnpsdmZsNGJXRDZyWktxeWpybitDSW1vb1RVCkc1b0tzTmduam9HY3AwdE1WdSti
            TlY0aHM0eUl4K0ozVHk4T0RMZkNjU2sKLS0tIHllbStmRDNpQ0RmdHl6SHplbGRy
            RGlxdWIrbHAyOEovWndPL0hhb21kWncK0Z0Hv8Rwir+4s4b36FwM3H1lBG/1vGkL
            yi6ywDxtUriBgf3MYxu+C3pHmK5Ak7QM7w0tSp6KL73AVz8e9BRX0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-24T00:22:50Z"
    mac: ENC[AES256_GCM,data:50eu7SKwIbY2bh1MqkuiCuWUN93A0kK2rgMMrwHTeWGKjtFHfS7g8Y5b5m/R41IZlyQOkZd9D7+ATM2C7jUI5nEg8FdTAx3WW8bWgJmEo5YjByK77sBX7rOkIOGGHO/F6zcwUQaa/Lyfw1F8LpiOlJKqjDvAeNLIlTM8QwbThcI=,iv:EqtbTRk6qiNu0zSSUin2Y648d6PZECNXndwtxz5TJq4=,tag:8PEJxdbXEN8pBbhnK91+1A==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
