keys:
  - &admin_soriphoono age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn

  - &cluster_adams age10mnx9lzy5ls2zl09qpsr4zryf9lys2qnv3a55832m436fzc0933q3sfn2t

creation_rules:
  - path_regex: talos/.*
    key_groups:
      - age:
          - *admin_soriphoono

  - path_regex: .*.yaml
    key_groups:
      - age:
          - *admin_soriphoono
          - *cluster_adams
    encrypted_regex: ^(data|stringData)$
