[project]
name = "guenivir"
revision = "1.0"

[profiles.default]
TF_VAR_proxmox_api_token = { description = "The proxmox api token to use in connecting to the local datacenter" }

[profiles.development]
TF_VAR_proxmox_api_url = { description = "The proxmox api url endpoint to use in connecting to the local datacenter", default = "https://pve-dev.xerus-augmented.ts.net" }

[profiles.production]
