[project]
name = "guenivir"
revision = "1.0"

[profiles.default]
TF_VAR_tailnet_fqdn = { description = "The FQDN for your tailnet's magic DNS, such as: <machine_name>.<FQDN>" }
TF_VAR_proxmox_api_token = { description = "The proxmox api token to use in connecting to the local datacenter" }

[profiles.development]

[profiles.production]
