apiVersion: v1
kind: Service
metadata:
  name: hello-world-envoy-proxy
  namespace: envoy-gateway-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/managed-by: envoy-gateway
    app.kubernetes.io/name: envoy
    gateway.envoyproxy.io/owning-gateway-name: hello-world-gateway
    gateway.envoyproxy.io/owning-gateway-namespace: hello-world
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 10080
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: hello-world-tunnel-binding
  namespace: hello-world
subjects:
  - name: wildcard
    spec:
      fqdn: "hello-world.cryptic-coders.net"
      # Stable service that fronts Envoy data-plane pods for hello-world.
      target: http://hello-world-envoy-proxy.envoy-gateway-system.svc.cluster.local:80
tunnelRef:
  kind: ClusterTunnel
  name: guenivir-testing-tunnel
