apiVersion: networking.cfargotunnel.com/v1alpha2
kind: Tunnel
metadata:
  name: hello-world-tunnel
  namespace: cloudflare-operator-system
spec:
  newTunnel:
    name: hello-world-guenivir-testing
  cloudflare:
    email: soriphoono@gmail.com
    domain: cryptic-coders.net
    secret: cloudflare-secrets
    accountId: b6e9a277e1c46db22032d0e2c04fb6ae
