services:
  traefik:
    image: traefik:v3.6.9 # Base version of v3 that supports docker API 1.44
    command:
      # Entrypoints
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.http.tls=true
      # Entrypoints Redirection (HTTP to HTTPS)
      - --entryPoints.web.http.redirections.entrypoint.to=websecure
      - --entryPoints.web.http.redirections.entrypoint.permanent=true
      # Docker Swarm Provider (direct socket access)
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.watch=true
      - --providers.swarm.exposedByDefault=false
      - --providers.swarm.network=reverse-proxy_public
      # Certificate Resolvers
      # 1. HTTP Challenge (Public)
      - --certificatesresolvers.http.acme.httpchallenge=true
      - --certificatesresolvers.http.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.http.acme.email=soriphoono@gmail.com
      - --certificatesresolvers.http.acme.storage=/letsecrypt/acme.json
      # 2. DNS Challenge (Cloudflare - for local/private domains)
      - --certificatesresolvers.dnsresolver.acme.dnschallenge=true
      - --certificatesresolvers.dnsresolver.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.dnsresolver.acme.dnschallenge.resolvers=100.100.100.100:53
      - --certificatesresolvers.dnsresolver.acme.email=soriphoono@gmail.com
      - --certificatesresolvers.dnsresolver.acme.storage=/letsecrypt/acme.json
      # API/Dashboard
      - --api.dashboard=true
      - --api.insecure=false
      # Logging
      - --log.level=INFO
      - --accesslog=true
      - --metrics.prometheus=true
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - public
    dns:
      - 100.100.100.100
    secrets:
      - cf_api_token
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/letsecrypt
    environment:
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_api_token
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        max_attempts: 3
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`proxy.admin.${DOMAIN_NAME}`)
        - traefik.http.routers.traefik.entrypoints=websecure
        - traefik.http.routers.traefik.service=api@internal
        - traefik.http.routers.traefik.tls.certresolver=dnsresolver
        - traefik.http.services.traefik.loadbalancer.server.port=8080

volumes:
  traefik-certs:

secrets:
  cf_api_token:
    file: ./secrets/cf_api_token

networks:
  public:
    driver: overlay
    attachable: true
