apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  timeout: 10m
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1h
  values:
    image:
      repository: traefik
      tag: v3.7.1
    deployment:
      replicas: 1
      kind: Deployment
    additionalArguments:
      - "--global.sendanonymoususage=false"
      - "--log.level=INFO"
    logs:
      general:
        format: json
      access:
        enabled: true
        format: json
    ports:
      web:
        port: 8000
        expose:
          default: true
        exposedPort: 80
      websecure:
        port: 8443
        expose:
          default: true
        exposedPort: 443
    ingressRoute:
      dashboard:
        enabled: true
        entryPoints: ["traefik"]
    providers:
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: true
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
    service:
      type: LoadBalancer
    persistence:
      enabled: false
    affinity: {}
    topologySpreadConstraints: []
