version: "3.8"

services:
  swarm-cd:
    image: ghcr.io/m-adawi/swarm-cd:1.10.0
    secrets:
      - source: age
        target: /secrets/age.key
    configs:
      - source: stacks
        target: /app/stacks.yml
        mode: 256
      - source: repos
        target: /app/repos.yml
        mode: 256
      - source: config
        target: /app/config.yml
        mode: 256
    environment:
      - SOPS_AGE_KEY_FILE=/secrets/age.key
      - DOMAIN_NAME=cryptic-coders.net
      - DOCKER_HOST=tcp://socket-proxy:2375
    networks:
      - public
      - socket-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    environment:
      - SWARM=1
      - STACKS=1
      - SERVICES=1
      - CONFIGS=1
      - SECRETS=1
      - NETWORKS=1
      - NODES=1
      - POST=1 # Required for swarm-cd to deploy stacks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-internal
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

secrets:
  age:
    file: /home/sphoono/.config/sops/age/keys.txt
configs:
  stacks:
    file: ./stacks.yml
  repos:
    file: ./repos.yml
  config:
    file: ./config.yml

networks:
  public:
    driver: overlay
    attachable: false
  socket-internal:
    driver: overlay
    internal: true
