shepherd:
  repo: cluster
  branch: main
  compose_file: docker/stacks/shepherd/docker-compose.yml

shared-services:
  repo: cluster
  branch: main
  compose_file: docker/stacks/shared-services/docker-compose.yml
