apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h
  values:
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    providers:
      kubernetesGateway:
        enabled: true
    gateway:
      enabled: false
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        port: 8000
        expose:
          default: true
      websecure:
        port: 8443
        expose:
          default: true
