apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-traefik
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 15m
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/infra/network/traefik
  prune: true
