apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Storage
  - longhorn.yaml
  # Databases
  - cloudnative-pg.yaml
  # Network
  - cert-manager.yaml
  - ingress-traefik.yaml
  - cloudflare-operator.yaml
