apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.cilium.io/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  interval: 1h
  timeout: 15m
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  chart:
    spec:
      chart: cilium
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 12h
  values:
    ipam:
      mode: kubernetes
    k8sServiceHost: 172.18.0.2
    k8sServicePort: 6443
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
