apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../controllers/network/metallb
  - ../controllers/network/envoy-gateway
  - ../controllers/network/cert-manager
  - ../controllers/observability/vmstack/operator
  - ../controllers/databases/cloudnative-pg
  - ../controllers/dns/cloudflare-operator
