apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../controllers/core
  - ../controllers/network/cilium
  - ../controllers/network/envoy-gateway
  - ../controllers/dns/cloudflare-operator
