apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../controllers/network/cert-manager
  - ../controllers/network/traefik
  - ../controllers/databases/cloudnative-pg
  - ../controllers/dns/cloudflare-operator
  - suplemental
  - ../controllers/databases/cloudnative-pg
