apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: cert-manager
  namespace: observability
  labels:
    monitoring.guenivir.io/stack: vmstack
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app.kubernetes.io/instance: cert-manager
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values:
          - controller
          - webhook
          - cainjector
  endpoints:
    - port: tcp-prometheus-servicemonitor
      path: /metrics
      interval: 30s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: metallb
  namespace: observability
  labels:
    monitoring.guenivir.io/stack: vmstack
spec:
  namespaceSelector:
    matchNames:
      - metallb-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: metallb
  podMetricsEndpoints:
    - targetPort: 7472
      path: /metrics
      interval: 30s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: envoy-gateway
  namespace: observability
  labels:
    monitoring.guenivir.io/stack: vmstack
spec:
  namespaceSelector:
    matchNames:
      - envoy-gateway-system
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-gateway
  podMetricsEndpoints:
    - targetPort: 19001
      path: /metrics
      interval: 30s
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: kubelet
  namespace: observability
  labels:
    monitoring.guenivir.io/stack: vmstack
spec:
  interval: 30s
  scrapeTimeout: 10s
  scheme: https
  tlsConfig:
    insecureSkipVerify: true
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - action: replace
      sourceLabels:
        - __address__
      targetLabel: __address__
      regex: ([^:]+)(:[0-9]+)?
      replacement: $1:10250
    - action: replace
      targetLabel: job
      replacement: kubelet
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: cadvisor
  namespace: observability
  labels:
    monitoring.guenivir.io/stack: vmstack
spec:
  interval: 30s
  scrapeTimeout: 10s
  scheme: https
  path: /metrics/cadvisor
  tlsConfig:
    insecureSkipVerify: true
    caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabelConfigs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - action: replace
      sourceLabels:
        - __address__
      targetLabel: __address__
      regex: ([^:]+)(:[0-9]+)?
      replacement: $1:10250
    - action: replace
      sourceLabels:
        - __metrics_path__
      targetLabel: metrics_path
    - action: replace
      targetLabel: job
      replacement: kubelet-cadvisor
