apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-credentials
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:Fcel9yA6VqO+F+flhbIQtbHev68e66trDq0WvMQKkxI9PxMdiuMYTgxRi9dWmx3RthVujgQ=,iv:1dCSbtVZo/79+5jMCrPXzoF2rV/I8M1+cTDhVt2u/zI=,tag:hJjz1xhjsfnzajmXVGq4lA==,type:str]
sops:
    age:
        - recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTVdiTHUzSXhVSUFTZC9s
            dnV6SjFYeE1QU09EalNVSmdJN1FORWJSOURBCnN0QitJb3JoYVVtV250cklLZlY1
            MFNzSFZEa0d0Um5WMmk5Wm4rUlh2ZFEKLS0tIE8vaTQ2WTQzYmlFT0tkRG84Rk1Y
            YjZKTzZQMGVtRGlNZFdYS05TYVIwQnMK+K9j4DmUQ/D6cMNcLPlLc6smAioWF1uc
            o3cR+jNROzuCSn6dLsn6dzxx4TL5wPox9A47e6bFXnXzYNbvoEmuKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcitPR2pXSnFJNSt0eS90
            WGlNN3JjSll0N2lFcyt0a3JyKzRIeDZoSEF3Citrd2MxVXJuSEUxSE9kT1dpTXpN
            OXJhZThHNmhtd1VqOUtscGUzQzJLQk0KLS0tIFl1cWx3Rkh0QkZCdSs4SmN0dXlC
            ZnJEc244RFhsUUpLT3hTN0tlK3d5bEEKdt4ZATTHMGzqbysjTARpC/xUZYZlrVdW
            qQCLdXcca9kkO6Hs+Il7qVc3VBfjBY5i2cw7kJzd/lUhbMNWzwKlHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T04:13:43Z"
    mac: ENC[AES256_GCM,data:lR3Kg6IiOOUYvFCfCn0c4j+/vnExggG6h+siCFzB4/GUZOYDEoedCnGXRZHutIOFpATcMmzvYn+COOxWZt2PkcdEX7vp5KSc3qrgX/dPBn/2wAh3IKbWFvivLq+ZzmkPiOgMubQIOZKFddQDNlr7NZfqimRYqeSzJndohYfYMdI=,iv:GwCdXbNnbrs+UjdpGZgsAsAsiSKRWRoALNuHB/tagE8=,tag:tR5eOc3Bp9ihdrIm4q3DLQ==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
