apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-credentials
    namespace: cloudflare-operator-system
type: Opaque
stringData:
    CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:TZGnrTbPy9XC6iyngXjY4iUfPB0SYzT/lJQvhxsPryQrDZegZPSoUmfTU/wQWMh8Mn0Cw9A=,iv:94YSU4yEqSySz48mSOiJnw1jZr96E9ihcewiiKrU41w=,tag:YbuzgM9GtHtGclv63fH3SA==,type:str]
sops:
    age:
        - recipient: age1frm803u6eet5dm4t6ugy77mkj4v980tqzfmn9wwnnk937me6dayqcyskw4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Y2NpOVVmbHJpRHBIRGRU
            Tk0vUHQvUTZ4VEdGWStjTzBXemVKUFo2M0hFCnVRK3NuQVZkVTEyenVleGhXMVFa
            UVR3OHZMR3FTa1NqNjlsMGtRQ095eGcKLS0tIFNWT2UvYUx3a2JzZ0tuTUxtMWM5
            ZU5zUG5DNC9QTk40Rmlpa3UybjBQeTQKiITmF5w2qJj14aNn0WdLbs97t8uq6XFd
            RHl/kNJqAZ5aPiuSrEKYichF9qLZlBaku3dv0SgJrfl+HptDy3kKwA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y4x8gzzcdhxvqaf9matt0eze3z3yxwx607avq4cexfkgwal4psesj39lvn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dXZNZ3M2aFpkZitNa2Fu
            aTkxOUluTk1EK2o3M2dyaHd5Qlh1NjBNUnkwCmhkdlVxaGFmSnhGS1k5d0p6VktY
            dTlXZnRJN0NId0JmZUVIa0kyVEp5cjAKLS0tIFozNzM0N09nRDVKanEybTc3elgz
            K0pBTGFJNDdzdEwwejIvRGRFTnE2aG8K19MwfiS8ScKQQ3WjQYLA/u7wUoG8d+36
            P5+GcFWtN5jd4vocOSZe7Yo9yBkwSWrAUoAMTVr018IGzPydql6zdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T14:56:49Z"
    mac: ENC[AES256_GCM,data:9r1OmQfI/4x2j1nelhxVWx+RvKVUVkQtOQj2IIf7MYWIa67eTob84m8fMJBCcbSFs1Q5QlqOTlQuRYHKG8Uwyhy0ccU5plqmhZPWT26ixMYiakpAx1Nx3nzFxT2x47+ny3EfeJk8GSRI3oG0gp0oopG8weUhxo/jhCS8JD5qrxA=,iv:qyHTGx1Wm/5K/JHwfeDbR2N2dFjnU1/qG8Wspr/T7bc=,tag:UFeOMfFymzmbOZRBvV1sFA==,type:str]
    encrypted_regex: ^(stringData|data)$
    version: 3.12.2
