apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  distribution:
    version: "2.8.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
    - source-watcher
  cluster:
    type: kubernetes
    size: small
    multitennant: true
    tenantDefaultServiceAccount: guenivir-core-flux
    networkPolicy: true
    objectLevelWorkloadIdentity: true
    multitenantWorkloadIdentity: true
    domain: cluster.local
  sync:
    kind: GitRepository
    url: https://github.com/controlplaneio-fluxcd/flux-operator.git
    ref: refs/heads/main
    path: k8s/clusters/staging/
