services:
  mongo:
    image: mongo:noble
    command: --quiet --wiredTigerCacheSizeGB 0.25
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-root-password
    secrets:
      - mongo-root-password
    networks:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
      labels:
        komodo.skip: # Prevent Komodo from stopping with StopAllContainers
secrets:
  mongo-root-password:
    file: ./secrets/mongo-root-password
volumes:
  mongo-data:
  mongo-config:
networks:
  mongo:
    driver: overlay
    attachable: true
