apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 15m
  dependsOn:
    - name: longhorn
    - name: cloudnative-pg
    - name: ingress-traefik
    - name: cloudflare-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/apps/auth/authentik
  prune: true
