apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-testing
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 15m
  dependsOn:
    - name: infra
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: ./k3s/apps/manifests/authentik
  prune: true
  wait: true
